# Change these first
owner: sysmike # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

assignees:
  - sysmike

sites:
  - name: Backup MX
    url: $BACKUPMX
    showAverageResponseTime: false
  - name: Blog
    url: $BLOG
    showAverageResponseTime: false
  - name: CS Wiki
    url: $CSWIKI
    showAverageResponseTime: false
  - name: Files
    url: $FILES
    showAverageResponseTime: false
  - name: Mail
    url: $MAIL
    showAverageResponseTime: false
  - name: Matomo
    url: $MATOMO
    showAverageResponseTime: false
  - name: PrivateBin
    url: $PRIVATEBIN
    showAverageResponseTime: false
  - name: Share
    url: $SHARE
    showAverageResponseTime: false
  - name: Teamspeak
    check: "tcp-ping"
    url: $TEAMSPEAK
    port: 10011
    showAverageResponseTime: false
  - name: vCard
    url: $VCARD
    showAverageResponseTime: false
  - name: Webserver
    check: "tcp-ping"
    url: $WEBSERVER
    port: 443
    showAverageResponseTime: false

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: UptimeRobot
      href: https://stats.uptimerobot.com/NloRtN8Ak
  robotsText: "User-agent: * \n Disallow: /"
  
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
